version: '3.8'
services:
  nodejs:
    build:
      context: .
    env_file: ./.env
    restart: always
    ports:
      - ${SIMPLE_API_PORT}:${SIMPLE_API_PORT}
    environment:
      - SIMPLE_API_HOST=${SIMPLE_API_HOST}
      - SIMPLE_API_PORT=${SIMPLE_API_PORT}
      - SIMPLE_DB_HOST=${SIMPLE_DB_HOST}
      - SIMPLE_DB_PORT=${SIMPLE_DB_PORT}
      - SIMPLE_DB_NAME=${SIMPLE_DB_NAME}
      - SIMPLE_DB_USERNAME=${SIMPLE_DB_USERNAME}
      - SIMPLE_DB_PASSWORD=${SIMPLE_DB_PASSWORD}
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    env_file: ./.env
    volumes:
      - './mongo-configs:/etc'
      - ./data:/data/db
    ports:
      - '${SIMPLE_DB_PORT}:${SIMPLE_DB_PORT}'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${SIMPLE_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${SIMPLE_DB_PASSWORD}
