version: '3.8'
services:
  nodejs:
    build:
      context: .
    env_file: ./.env
    restart: always
    ports:
      - 8080:${SIMPLE_API_PORT}
    environment:
      - SIMPLE_API_HOST=${SIMPLE_API_HOST}
      - SIMPLE_API_PORT=${SIMPLE_API_PORT}
      - SIMPLE_DB_HOST=${SIMPLE_DB_HOST}
      - SIMPLE_DB_PORT=${SIMPLE_DB_PORT}
      - SIMPLE_DB_NAME=${SIMPLE_DB_NAME}
    expose:
      - ${SIMPLE_API_HOST}
    networks:
      - local
  mongodb:
    container_name: mongodb
    image: mongodb
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'

networks:
  local:
    driver: bridge