version: '3.8'
services:
  nodejs:
    build:
      context: .
    env_file: ./.env
    restart: always
    ports:
      - ${SIMPLE_API_PORT}:${SIMPLE_API_PORT}
    environment:
      - SIMPLE_API_HOST=${SIMPLE_API_HOST}
      - SIMPLE_API_PORT=${SIMPLE_API_PORT}
      - SIMPLE_DB_HOST=${SIMPLE_DB_HOST}
      - SIMPLE_DB_PORT=${SIMPLE_DB_PORT}
      - SIMPLE_DB_NAME=${SIMPLE_DB_NAME}
      - SIMPLE_DB_USER=${SIMPLE_DB_USER}
      - SIMPLE_DB_PASS=${SIMPLE_DB_PASS}
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:6.0
    env_file: ./.env
    volumes:
      - ./data:/data/db
    ports:
      - '${SIMPLE_DB_PORT}:${SIMPLE_DB_PORT}'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SIMPLE_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${SIMPLE_DB_PASS}
